yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='all posts'),
    path('group/<slug:slug>/', views.group_posts, name='sorted_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Ссылка')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)
        verbose_name_plural = 'Группы постов'


class Post(CreatedModel):
    text = models.TextField(verbose_name='Текст поста',
                            help_text='Введите текст поста',)

    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор',
                               )
    group = models.ForeignKey(Group,
                              blank=True,
                              null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              verbose_name='Группа',
                              help_text=('Группа, '
                                         'к которой будет относиться пост'))
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:settings.SYMBOL_RESTRICTION_FOR_POST_NAME]

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = 'Посты'


class Comment(CreatedModel):
    post = models.ForeignKey(Post,
                             blank=True,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name='Комментарий',
                             help_text=('Комментарий под '
                                        'постом'))
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments',
                               verbose_name='Автор',
                               )
    text = models.TextField(verbose_name='Текст комментария',
                            help_text='Введите текст комментария',)

    def __str__(self):
        return self.text[:settings.SYMBOL_RESTRICTION_FOR_POST_NAME]

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower',
                             )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following',
                               )

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=~models.Q(
                    user=models.F('author')
                ), name='user=author'),
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='users follow on uniq authors'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)
        help_texts = {'text': 'Текст нового поста',
                      'group': 'Группа, к которой будет относиться пост',
                      'image': 'Картинка'}
        labels = {'text': 'Текст поста',
                  'group': 'Группа',
                  'image': 'Картинка'}


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

    def clean_text(self):
        """replace the second name from
        black list on *** """
        data = self.cleaned_data['text']
        black_list = {
            'бузова': '******',
            'донцова': '******',
        }
        data = data.lower()
        temp_data = data
        for second_name, replacing in black_list.items():
            upd_data = temp_data.replace(second_name, replacing)
            temp_data = upd_data
        upd_data = upd_data.capitalize()
        return upd_data

yatube/posts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.conf import settings
from django.db.models import QuerySet

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm


def paginator_func(some_query: QuerySet,
                   request: HttpRequest,
                   list_per_page:
                   int = settings.SORTED_VALUES_AMOUNT,) -> Paginator:
    """To return Paginator object"""
    paginator: Paginator = Paginator(some_query, list_per_page)
    page_number: int = request.GET.get('page')
    page_obj: Paginator = paginator.get_page(page_number)
    return page_obj


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.select_related('author', 'group').all()
    page_obj = paginator_func(some_query=post_list,
                              request=request,)
    context = {'page_obj': page_obj, }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author',).all()
    page_obj = paginator_func(some_query=post_list,
                              request=request,)
    context = {'group': group,
               'page_obj': page_obj, }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group').all()
    page_obj = paginator_func(some_query=post_list,
                              request=request,)

    if request.user.is_authenticated and Follow.objects.filter(
            user=request.user,
            author=author).exists():
        following = True
    else:
        following = False

    context = {'author': author,
               'page_obj': page_obj,
               'following': following}
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post.objects.select_related('author'), pk=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {'post': post,
               'comments': comments,
               'form': form,
               }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    context = {'form': form}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)

    context = {'form': form,
               'is_edit': True, }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts = Post.objects.filter(
        author__following__user=request.user
    ).select_related('author', 'group')
    page_obj = paginator_func(some_query=posts,
                              request=request,)
    context = {'page_obj': page_obj, }

    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)

    if request.user.username != username:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect(
        'posts:profile',
        author
    )


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)

    subscription = author.following.filter(user=request.user)

    subscription.delete()
    return redirect(
        'posts:profile',
        author
    )

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}  
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
 
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост 
            {% endif %}
                         
          </div>
          <div class="card-body">        
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}

            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}      
                          
              <div class="form-group row my-3 p-3">
                <label for="{{ form.text.id_for_label }}">
                  {{ form.text.label }}
                  
                 <span class="required text-danger">*</span>
                  
                </label>
                
                  {% if is_edit %}
                    {{ form.text}}
                  {% else %}
                  <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                  {% endif %}
                </textarea>                
                
                <small id="{{ form.text.id_for_label }}-help" class="form-text text-muted"> 
                  {{ form.text.help_text|safe }}
                </small>
                                 
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="{{ form.group.id_for_label }}">
                  {{ form.group.label }}               
                </label>
                <select name="group" class="form-control" id="id_group">
                <option selected aria-required="false" > 
                  {% for groupe_item in form.group  %}  
                    {{ groupe_item }} 
                       
                  {% endfor %} 
                </option>  
                </select>
                <small id="{{ form.group.id_for_label }}-help" class="form-text text-muted">
                  {{ form.group.help_text|safe }}
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="{{ form.image.id_for_label }}">
                  {{ form.image.help_text|safe }}                    
                </label>
                <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
              </div>

              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %} Подписки на авторов {% endblock %}

{% block content %}
  <div class="container">
    {%with follow=True%}
      {% include 'posts/includes/switcher.html' %}        
      <h1>Подписки на авторов</h1>
    {%endwith%} 
    {% for post in page_obj %}
      {% with AUTHOR_NAME_SHOW=True PRINT_LINK=True  DEATAILED_INFO=True %}
        {% include 'includes/post_card.html' %}
      {% endwith %}
  
    {% empty %}
      <p>No_data</p>
    {% endfor %}

  {% include 'posts/includes/paginator.html' %} 
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %} Записи сообщества {{ group }} {% endblock %}  
{% block content %}
  <div class="container py-5">  
    <h1>Записи сообщества: {{ group }}</h1>
    <p>
      {{ group.description|linebreaks }}
    </p>
    
    {% for post in page_obj %}
      {% with AUTHOR_NAME_SHOW=True PRINT_LINK=True DEATAILED_INFO=True %}  
        {% include 'includes/post_card.html' %}
      {% endwith %}  
      
    {% empty %}
        <p>No_data</p>
    {% endfor %} 
  {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

          

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %} Последние обновления на сайте {% endblock %}

{% block content %}
  <div class="container">        
    {%with index=True%}
      {% include 'posts/includes/switcher.html'%}
      <h1>Последние обновления на сайте</h1>
    {%endwith%}
  
  {% cache 20 index_page request.user.username page_obj.number %}
    {% for post in page_obj %}
      {% with AUTHOR_NAME_SHOW=True PRINT_LINK=True  DEATAILED_INFO=True %}
        {% include 'includes/post_card.html' %}
      {% endwith %}
  
    {% empty %}
      <p>No_data</p>
    {% endfor %}
{% endcache %}
  {% include 'posts/includes/paginator.html' %} 
{% endblock %}
       

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %} {{ post.text|truncatewords:30 }} {% endblock %}

{% block content %}    
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.created|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }}    
            <a href="{% url 'posts:sorted_posts' post.group.slug  %}">
            все записи группы
            </a>
        {% endif %}

        <li class="list-group-item">
          Автор: {{post.author.get_full_name}}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{ post.author.posts.count }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username  %}">
            все посты пользователя
          </a>
            
        </li>
      </ul>
    </aside>

    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}  
      <p>
        {{post.text|linebreaksbr}}
      </p>
      {% if post.author == request.user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk%}">
          редактировать запись
        </a>
      {% endif %}
      {% include 'posts/includes/post_comment.html'%}
    </article>
  </div> 
{% endblock %}
    

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
  <div class="mb-5">     
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    <h5>Всего подписчиков: {{author.follower.count}}</h5>
    <h5>Всего подписок: {{author.following.count}}</h5>
    {% if request.user.is_authenticated and request.user != author %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
    {% for post in page_obj %}
      {% with PRINT_LINK=True DEATAILED_INFO=True AUTHOR_NAME_SHOW=False %}  
        {% include 'includes/post_card.html' %}
      {% endwith %}  
        
    {% empty %}
      <p>No_data</p>
    {% endfor %}
     
        
    {% include 'posts/includes/paginator.html' %} 
  </div>
{% endblock %}